"use client"

import { useEffect, useState } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Switch } from "@/components/ui/switch"

type Plan = { id: string; name: string; description: string; price: number; billing_interval: string; min_duration_months: number; cancellation_notice_months: number; newcomer_only: boolean; includes_discount: boolean; discount_percent: number | null; active: boolean }
const empty = { name: "", description: "", price: "", billing_interval: "monthly", min_duration_months: "1", cancellation_notice_months: "0", newcomer_only: false, includes_discount: false, discount_percent: "10", active: true }
export default function AdminMitgliedschaftenPage() {
  const [plans, setPlans] = useState<Plan[]>([]); const [form, setForm] = useState(empty); const [message, setMessage] = useState("")
  const load = () => fetch("/api/admin/memberships").then((r) => r.json()).then((d) => setPlans(d.plans ?? []))
  useEffect(() => { load() }, [])
  async function save() { const r = await fetch("/api/admin/memberships", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, price: Number(form.price), min_duration_months: Number(form.min_duration_months), cancellation_notice_months: Number(form.cancellation_notice_months), discount_percent: Number(form.discount_percent) }) }); const d = await r.json(); setMessage(r.ok ? "Membership-Stufe gespeichert." : d.error ?? "Fehler."); if (r.ok) { setForm(empty); load() } }
  return <main className="mx-auto max-w-6xl px-6 py-10"><h1 className="mb-8 text-4xl font-bold">Memberships verwalten</h1><div className="grid gap-8 lg:grid-cols-[1fr_1.4fr]"><Card><CardHeader><CardTitle>Neue Stufe</CardTitle></CardHeader><CardContent className="space-y-4"><div><Label>Name</Label><Input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></div><div><Label>Beschreibung</Label><Input value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></div><div><Label>Preis</Label><Input type="number" min="0" value={form.price} onChange={(e) => setForm({ ...form, price: e.target.value })} /></div><div><Label>Abbuchung</Label><select className="w-full rounded-md border bg-background p-2" value={form.billing_interval} onChange={(e) => setForm({ ...form, billing_interval: e.target.value })}><option value="monthly">Monatlich</option><option value="quarterly">Vierteljährlich</option><option value="yearly">Jährlich</option></select></div><div className="grid grid-cols-2 gap-3"><div><Label>Mindestmonate</Label><Input type="number" min="1" value={form.min_duration_months} onChange={(e) => setForm({ ...form, min_duration_months: e.target.value })} /></div><div><Label>Kündigungsfrist Monate</Label><Input type="number" min="0" value={form.cancellation_notice_months} onChange={(e) => setForm({ ...form, cancellation_notice_months: e.target.value })} /></div></div><label className="flex items-center justify-between text-sm">Neukommer-Abo <Switch checked={form.newcomer_only} onCheckedChange={(v) => setForm({ ...form, newcomer_only: v })} /></label><label className="flex items-center justify-between text-sm">Rabatt inklusive <Switch checked={form.includes_discount} onCheckedChange={(v) => setForm({ ...form, includes_discount: v })} /></label>{form.includes_discount && <div><Label>Rabatt %</Label><Input type="number" min="1" max="100" value={form.discount_percent} onChange={(e) => setForm({ ...form, discount_percent: e.target.value })} /></div>}<Button onClick={save}>Stufe erstellen</Button>{message && <p className="text-sm text-primary">{message}</p>}</CardContent></Card><div className="space-y-4">{plans.map((plan) => <Card key={plan.id}><CardHeader className="flex flex-row items-center justify-between"><CardTitle>{plan.name}</CardTitle><Switch checked={plan.active} onCheckedChange={async (active) => { await fetch("/api/admin/memberships", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: plan.id, active }) }); load() }} /></CardHeader><CardContent><p className="text-sm text-muted-foreground">{plan.description}</p><p className="mt-2 font-semibold">{Number(plan.price).toFixed(2)} € / {plan.billing_interval}</p><p className="text-sm">Mindestlaufzeit: {plan.min_duration_months} Monat(e), Kündigungsfrist: {plan.cancellation_notice_months} Monat(e)</p></CardContent></Card>)}</div></div></main>
}
